### ISSUE TITLE
Unit tests error

### ISSUE THREAD

**Issue by vasile33** [hslayers/hslayers-ng#115]
hslayers-ng seems to run just fine. However, I'm getting the bellow error when I try to run nmp test:

npm test

> hslayer-ng@0.4.0 pretest /var/www/html/hslayers-ng
> npm install

> hslayer-ng@0.4.0 postinstall /var/www/html/hslayers-ng
> bower --allow-root install

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm WARN karma-requirejs@0.2.6 requires a peer of requirejs@^2.1.0 but none was installed.

> hslayer-ng@0.4.0 test /var/www/html/hslayers-ng
> karma start test/karma.conf.js

09 05 2017 01:10:21.051:WARN [plugin]: Error during loading "/var/www/html/hslayers-ng/node_modules/karma-requirejs" plugin:
  Cannot find module 'requirejs'
/var/www/html/hslayers-ng/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:requirejs"! (Resolving: framework:requirejs)
    at error (/var/www/html/hslayers-ng/node_modules/di/lib/injector.js:22:12)
    at Object.parent.get (/var/www/html/hslayers-ng/node_modules/di/lib/injector.js:9:13)
    at get (/var/www/html/hslayers-ng/node_modules/di/lib/injector.js:54:19)
    at /var/www/html/hslayers-ng/node_modules/karma/lib/server.js:138:20
    at Array.forEach (native)
    at Server._start (/var/www/html/hslayers-ng/node_modules/karma/lib/server.js:137:21)
    at invoke (/var/www/html/hslayers-ng/node_modules/di/lib/injector.js:75:15)
    at Server.start (/var/www/html/hslayers-ng/node_modules/karma/lib/server.js:102:18)
    at Object.exports.run (/var/www/html/hslayers-ng/node_modules/karma/lib/cli.js:243:26)
    at Object.<anonymous> (/var/www/html/hslayers-ng/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
npm ERR! Test failed.  See above for more details.

**Comment by raitisbe** [comment]
karma.conf.js and test-main.js file was quite out of date and some dependencies where not specified.

**Comment by vasile33** [comment]
Hi @raitisbe,

Thank you for the fix. However, something else was broken. The examples are no longer working. Also, some optional library is not loaded (“NetworkError: 404 Not Found - http://frontend.eo4see.info.uvt.ro/hslayers-ng/gitsha.js”).

Best,
Vasile

**Comment by raitisbe** [comment]
It might be fixed now in https://github.com/hslayers/hslayers-ng/commit/f13936e745b110f6a68869db2b1040b21753dedc. Gitsha is just a small file which is used for cache busting and not always exists on the server but it was not the source of the problem.
